import Head from "next/head";
import Link from "next/link";
import styles from "../../styles/Users.module.css";

export default function Home({ result }) {
  return (
    <div className="container">
      <Head>
        <title>Serverless Demo | Users</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {result.response.map((data) => (
          <Link key={data.id} href={`/users/${data.id}`}>
            <a>
              <ul>
                <p>{data.username}</p>
                <p>{data.email}</p>
                <p>{data.address.city}</p>
                <hr></hr>
              </ul>
            </a>
          </Link>
        ))}
      </main>
    </div>
  );
}

export async function getStaticProps(context) {
  const result = await (
    await fetch("https://next-function-mauve.vercel.app/api/users/")
  ).json();
  return {
    props: {
      result,
    },
  };
}
