import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

export default function Home({ result }) {
  return (
    <div>
      <Head>
        <title>How api works</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {/* {result.response.map((data) => (
          <Link key={data.id} href={`/users/${data.id}`}>
            <a>
              <ul>
                <p>{data.username}</p>
                <p>{data.email}</p>
                <p>{data.address.city}</p>
                <hr></hr>
              </ul>
            </a>
          </Link>
        ))} */}
      </main>
    </div>
  );
}

export async function getStaticProps(context) {
  // const result = await (await fetch("http://localhost:8000/api/users/")).json();
  return {
    props: {
      // result,
      hello: "hello",
    },
  };
}
